# Generated by Django 5.2.6 on 2025-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start date and time in UTC'),
        ),
    ]
