# Generated by Django 5.2.6 on 2025-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0002_alter_activity_distance_alter_activity_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='volunteer_event',
            field=models.IntegerField(blank=True, null=True, verbose_name='Event number volunteered at that parkrun location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Parkrun location'),
        ),
    ]
