# Generated by Django 5.2.8 on 2025-12-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0003_activity_volunteer_event_alter_activity_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer_event',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Event number volunteered at that parkrun location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parkrun_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
