# Generated by Django 5.2.8 on 2025-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0004_alter_activity_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
