# Generated by Django 5.2.8 on 2025-12-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0005_activity_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal_duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
