# Generated by Django 6.0.1 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bpaml_strava', '0006_user_goal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='strava_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
